#Web服务器：apache | nginx，通过交互式选择获取
nextcloud_webs: apache

moodle_vhost_dir: /etc/httpd/vhost
moodle_vhost_src: vhost.conf
moodle_service: httpd
moodle_owner: apache
nextcloud_name: "nextcloud"
nextcloud_title: "NextCloud"
nextcloud_download_url: "https://github.com/nextcloud/server.git"
nextcloud_version: "v18.0.0"  #版本号需定期维护