---
#引入PHP运行环境元数据，并初始化

- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Create var for this playbook
- set_fact:
    nextcloud_vhost_dir: "{{php_runtime_meta[ansible_os_family][nextcloud_webs].vhost_dir}}"
    nextcloud_vhost_src: "{{php_runtime_meta[ansible_os_family][nextcloud_webs].vhost_src}}"
    nextcloud_service: "{{php_runtime_meta[ansible_os_family][nextcloud_webs].service}}"
    nextcloud_owner: "{{php_runtime_meta[ansible_os_family][nextcloud_webs].owner}}"

- debug:
    msg: runtime {{ nextcloud_vhost_dir }}, {{nextcloud_vhost_src}}, {{nextcloud_service}}, {{nextcloud_owner}}, {{nextcloud_webs}}, {{ansible_distribution}}

# NextCloud
- name: Remove extra dir
  shell: |
    rm -rf /data/wwwroot/*{{nextcloud_name}}*

- name: Download NextCloud
  unarchive:
    src: "{{nextcloud_download_url}}"
    dest: /data/wwwroot/nextcloud
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{nextcloud_name}}" ]; then mv *{{nextcloud_name}}* {{nextcloud_name}}; fi

-  name: Set OPCache for NextCloud
   copy: src=opcache.ini dest=/etc/php.d/opcache.ini

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted

- name: Permission occ
  file:
    path: /data/wwwroot/nextcloud/occ
    state: file
    mode: "u+x,g+x"

- name: copy config
  copy: src=config.php  dest=/data/wwwroot/nextcloud/config

- name: Set NextCloud Job
  command: php -f /data/wwwroot/nextcloud/cron.php

- name: NextCloud cron
  cron:
    name: "nextcloud cron"
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: "{{nextcloud_owner}}"
    job: "php -f /data/wwwroot/nextcloud/cron.php"

# 系统通用

- name: Permission directory
  shell: |
    find /data/wwwroot -type d -exec chmod 750 {} \;
    find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理

- block:
  - name: change owner&group
    shell: chown -R {{nextcloud_owner}}:{{nextcloud_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    template: src={{nextcloud_vhost_src}} dest={{nextcloud_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{nextcloud_service}} state=restarted enabled=yes