---
#引入PHP运行环境元数据，并初始化

include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

nextcloud_vhost_dir: php_runtime_meta.{{ansible_distribution}}.{{nextcloud_webs}}.vhost_dir
nextcloud_vhost_src: php_runtime_meta.{{ansible_distribution}}.{{nextcloud_webs}}.vhost_src
nextcloud_service: php_runtime_meta.{{ansible_distribution}}.{{nextcloud_webs}}.service
nextcloud_owner: php_runtime_meta.{{ansible_distribution}}.{{nextcloud_webs}}.owner

# 9panel
- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["NextCloud"];'

# NextCloud
- name: Delete www.example.com directory
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Create Directory
  file:
    path: /data/wwwroot/nextcloud
    state: directory
    mode: 0755

- name: Download NextCloud
  git:
    repo: https://github.com/nextcloud/server.git
    dest: /data/wwwroot/nextcloud
    version: "{{nextcloud_version}}"

-  name: Set OPCache for NextCloud
   copy: src=opcache.ini dest=/etc/php.d/opcache.ini

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted

- name: Permission occ
  file:
    path: /data/wwwroot/nextcloud/occ
    state: file
    mode: "u+x,g+x"

- name: copy config
  copy:
    src: config.php
    dest: /data/wwwroot/nextcloud/config

- name: Set NextCloud Job
  command: php -f /data/wwwroot/nextcloud/cron.php


# 系统通用

- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;


# 根据不同的基础环境分别处理

- block:
  - name: change owner&group for Apache
    shell: chown -R {{nextcloud_owner}}:{{nextcloud_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    template: src={{nextcloud_vhost_src}} dest={{nextcloud_vhost_dir}}

  - name: NextCloud cron
    cron:
      name: "NextCloud cron"
      minute: "*/15"
      hour: "*"
      day: "*"
      month: "*"
      weekday: "*"
      user: {{nextcloud_owner}}
      job: "php -f /data/wwwroot/nextcloud/cron.php"
    
  - name: restart Apache or Nginx
    service: name={{nextcloud_service}} state=restarted enabled=yes